const ARCHITECTURE_RULES = {
  requiredTargetDirectories: [
    'src/domains/chat',
    'src/domains/account',
    'src/domains/billing',
    'src/domains/settings',
    'src/domains/access-control',
    'src/domains/content',
    'src/surfaces/admin',
    'src/infra/platform',
    'src/infra/adapters',
    'src/infra/runtime',
  ],
  legacyArchitectureDirectories: [
    'src/core',
    'src/features',
    'src/shared/models',
    'src/shared/services',
  ],
  dirtyImports: [
    '@/shared/models',
    '@/shared/services',
    '@/core',
    '@/features',
  ],
  publicCompositionPathPatterns: [],
  domainForbiddenImports: [
    '^@/app(?:/|$)',
    '^@/surfaces(?:/|$)',
    '^@/infra/platform(?:/|$)',
    '^@/infra/adapters(?:/|$)',
    '^@/shared/schemas/api(?:/|$)',
  ],
  applicationAllowedPlatformImports: [
    '^@/infra/platform/logging(?:/|$)',
    '^@/infra/platform/request-context(?:/|$)',
  ],
  appOnlyFacades: [],
  appOnlyFacadeImportPatterns: [],
  appAdminForbiddenImports: [
    '^@/domains/[^/]+/infra(?:/|$)',
    '^@/infra/adapters(?:/|$)',
  ],
  memberSettingsForbiddenImports: [
    '^@/domains/billing/infra(?:/|$)',
    '^@/infra/adapters/payment(?:/|$)',
  ],
  memberActivityForbiddenImports: [
    '^@/domains/chat/infra(?:/|$)',
    '^@/domains/ai/infra(?:/|$)',
  ],
  memberChatForbiddenImports: ['^@/domains/chat/infra(?:/|$)'],
  paymentCallbackRouteForbiddenImports: [
    '^@/domains/billing/infra(?:/|$)',
    '^@/infra/adapters/payment(?:/|$)',
  ],
  surfacesAdminForbiddenImports: [
    '^@/domains/[^/]+/infra(?:/|$)',
    '^@/infra/adapters(?:/|$)',
  ],
  applicationPlatformImportExceptions: [
    {
      file: 'src/domains/content/application/local-content.tsx',
      imports: [
        '^@/infra/platform/brand/placeholders(?:\\.server)?$',
        '^@/infra/platform/brand/placeholders-react\\.server$',
      ],
      reason:
        'Local MDX content still performs public brand placeholder projection until content rendering is split from content query.',
    },
    {
      file: 'src/domains/settings/application/settings-store.ts',
      imports: ['^@/infra/platform/auth/oauth-spike-config$'],
      reason:
        'Settings store seeds local OAuth spike config before DB settings exist; this must not expand to auth session or guard imports.',
    },
  ],
  applicationFanOutLimit: 2,
  queryViewAllowedSameDomainApplicationPathPattern:
    '^(?:[^/]+\\.)?(?:query|view|contracts)(?:\\.[^/.]+)?$',
  aggregation: {
    pathPattern: '/application/aggregation/[^/]+\\.aggregation\\.ts$',
    marker: 'architecture-exception: cross-domain-aggregation',
    reasonPattern: 'reason:\\s*\\S+',
    perDomainBudget: 1,
    totalBudget: 5,
  },
  orchestration: {
    pathPattern: '/application/orchestration/[^/]+\\.orchestration\\.ts$',
    marker: 'architecture-exception: cross-domain-orchestration',
    reasonPattern: 'reason:\\s*\\S+',
    ownerPattern: 'owner:\\s*\\S+',
    failureCompensationPattern: 'failure-compensation:\\s*\\S+',
    perDomainBudget: 1,
    totalBudget: 5,
  },
  sharedLibAllowedPathPatterns: [
    '^action/',
    '^api/',
    '^date/',
    '^dom/',
    '^fetch/',
    '^i18n/',
    '^providers/provider-registry(?:\\.test)?\\.ts$',
    '^runtime/',
    '^brand-url(?:\\.test)?\\.ts$',
    '^cache\\.ts$',
    '^callback-url\\.ts$',
    '^cloudflare-local-smoke-config(?:\\.test)?\\.ts$',
    '^config-consistency(?:\\.test)?\\.ts$',
    '^cookie\\.ts$',
    '^email\\.ts$',
    '^env\\.ts$',
    '^errors\\.ts$',
    '^general-ui(?:\\.client|\\.schema)?\\.ts$',
    '^hash\\.ts$',
    '^json\\.ts$',
    '^localize-callback-url\\.ts$',
    '^map-cleanup(?:\\.test)?\\.ts$',
    '^middleware-request-headers(?:\\.test)?\\.ts$',
    '^post-date\\.ts$',
    '^storage-public-url\\.ts$',
    '^support-email(?:\\.test)?\\.ts$',
    '^time\\.ts$',
    '^utf8\\.ts$',
    '^utils\\.ts$',
  ],
  sharedLibForbiddenSemanticNames: [
    'billing',
    'payment',
    'credits',
    'rbac',
    'checkout',
    'webhook',
    'auth-session',
    'brand-identity',
    'landing-visibility',
    'seo',
  ],
  settingsForbiddenBusinessImports: [
    'billing',
    'chat',
    'account',
    'payment',
    'rbac',
  ],
};

module.exports = {
  ARCHITECTURE_RULES,
};
