/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings_'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NoPermissionRouteImport } from './routes/no-permission'
import { Route as MyImagesRouteImport } from './routes/my-images'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs_'
import { Route as ChatRouteImport } from './routes/chat_'
import { Route as BlogRouteImport } from './routes/blog_'
import { Route as AiMusicGeneratorRouteImport } from './routes/ai-music-generator'
import { Route as AiImageGeneratorRouteImport } from './routes/ai-image-generator'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AdminRouteImport } from './routes/admin_'
import { Route as ActivityRouteImport } from './routes/activity_'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentsRouteImport } from './routes/settings/payments'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChatSplatRouteImport } from './routes/chat/$'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as ActivityFeedbacksRouteImport } from './routes/activity/feedbacks'
import { Route as ActivityChatsRouteImport } from './routes/activity/chats'
import { Route as ActivityAiTasksRouteImport } from './routes/activity/ai-tasks'
import { Route as LocaleSignUpRouteImport } from './routes/$locale/sign-up'
import { Route as LocaleSignInRouteImport } from './routes/$locale/sign-in'
import { Route as LocaleSettingsRouteImport } from './routes/$locale/settings_'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale/reset-password'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocaleNoPermissionRouteImport } from './routes/$locale/no-permission'
import { Route as LocaleMyImagesRouteImport } from './routes/$locale/my-images'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleDocsRouteImport } from './routes/$locale/docs_'
import { Route as LocaleChatRouteImport } from './routes/$locale/chat_'
import { Route as LocaleBlogRouteImport } from './routes/$locale/blog_'
import { Route as LocaleAiMusicGeneratorRouteImport } from './routes/$locale/ai-music-generator'
import { Route as LocaleAiImageGeneratorRouteImport } from './routes/$locale/ai-image-generator'
import { Route as LocaleAdminRouteImport } from './routes/$locale/admin_'
import { Route as LocaleActivityRouteImport } from './routes/$locale/activity_'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as SettingsInvoicesRetrieveRouteImport } from './routes/settings/invoices/retrieve'
import { Route as SettingsBillingRetrieveRouteImport } from './routes/settings/billing_/retrieve'
import { Route as SettingsBillingCancelRouteImport } from './routes/settings/billing_/cancel'
import { Route as SettingsApikeysCreateRouteImport } from './routes/settings/apikeys_/create'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'
import { Route as ApiUserSelfDetailsRouteImport } from './routes/api/user/self-details'
import { Route as ApiUserGetUserCreditsRouteImport } from './routes/api/user/get-user-credits'
import { Route as ApiTtsQuotaRouteImport } from './routes/api/tts/quota'
import { Route as ApiTtsHistoryRouteImport } from './routes/api/tts/history'
import { Route as ApiTtsGenerateRouteImport } from './routes/api/tts/generate'
import { Route as ApiStorageUploadImageRouteImport } from './routes/api/storage/upload-image'
import { Route as ApiRemoverUploadRouteImport } from './routes/api/remover/upload'
import { Route as ApiRemoverJobsRouteImport } from './routes/api/remover/jobs'
import { Route as ApiRemoverCleanupRouteImport } from './routes/api/remover/cleanup'
import { Route as ApiPaymentNotifyRouteImport } from './routes/api/payment/notify'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api/payment/callback'
import { Route as ApiEmailVerifyCodeRouteImport } from './routes/api/email/verify-code'
import { Route as ApiEmailTestRouteImport } from './routes/api/email/test'
import { Route as ApiEmailSendEmailRouteImport } from './routes/api/email/send-email'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs/search'
import { Route as ApiConfigGetConfigsRouteImport } from './routes/api/config/get-configs'
import { Route as ApiChatNewRouteImport } from './routes/api/chat/new'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat/messages'
import { Route as ApiChatListRouteImport } from './routes/api/chat/list'
import { Route as ApiChatInfoRouteImport } from './routes/api/chat/info'
import { Route as ApiBackgroundRemoverRemoveRouteImport } from './routes/api/background-remover/remove'
import { Route as ApiBackgroundRemoverCleanupRouteImport } from './routes/api/background-remover/cleanup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiQueryRouteImport } from './routes/api/ai/query'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiAiCapabilitiesRouteImport } from './routes/api/ai/capabilities'
import { Route as LocaleSettingsSecurityRouteImport } from './routes/$locale/settings/security'
import { Route as LocaleSettingsProfileRouteImport } from './routes/$locale/settings/profile'
import { Route as LocaleSettingsPaymentsRouteImport } from './routes/$locale/settings/payments'
import { Route as LocaleSettingsCreditsRouteImport } from './routes/$locale/settings/credits'
import { Route as LocaleSettingsBillingRouteImport } from './routes/$locale/settings/billing'
import { Route as LocaleSettingsApikeysRouteImport } from './routes/$locale/settings/apikeys'
import { Route as LocaleDocsSplatRouteImport } from './routes/$locale/docs/$'
import { Route as LocaleChatSplatRouteImport } from './routes/$locale/chat/$'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as LocaleAdminSplatRouteImport } from './routes/$locale/admin/$'
import { Route as LocaleActivityFeedbacksRouteImport } from './routes/$locale/activity/feedbacks'
import { Route as LocaleActivityChatsRouteImport } from './routes/$locale/activity/chats'
import { Route as LocaleActivityAiTasksRouteImport } from './routes/$locale/activity/ai-tasks'
import { Route as SettingsApikeysIdEditRouteImport } from './routes/settings/apikeys_/$id/edit'
import { Route as SettingsApikeysIdDeleteRouteImport } from './routes/settings/apikeys_/$id/delete'
import { Route as ApiTtsDownloadIdRouteImport } from './routes/api/tts/download/$id'
import { Route as ApiRemoverJobsIdRouteImport } from './routes/api/remover/jobs/$id'
import { Route as ApiRemoverDownloadLowResRouteImport } from './routes/api/remover/download/low-res'
import { Route as ApiRemoverDownloadHighResRouteImport } from './routes/api/remover/download/high-res'
import { Route as ApiBackgroundRemoverResultIdRouteImport } from './routes/api/background-remover/result/$id'
import { Route as ApiBackgroundRemoverDownloadIdRouteImport } from './routes/api/background-remover/download/$id'
import { Route as ApiAiNotifyProviderRouteImport } from './routes/api/ai/notify/$provider'
import { Route as ActivityAiTasksIdRefreshRouteImport } from './routes/activity/ai-tasks_/$id/refresh'
import { Route as LocaleSettingsInvoicesRetrieveRouteImport } from './routes/$locale/settings/invoices/retrieve'
import { Route as LocaleSettingsBillingRetrieveRouteImport } from './routes/$locale/settings/billing_/retrieve'
import { Route as LocaleSettingsBillingCancelRouteImport } from './routes/$locale/settings/billing_/cancel'
import { Route as LocaleSettingsApikeysCreateRouteImport } from './routes/$locale/settings/apikeys_/create'
import { Route as LocaleBlogCategorySlugRouteImport } from './routes/$locale/blog/category/$slug'
import { Route as LocaleSettingsApikeysIdEditRouteImport } from './routes/$locale/settings/apikeys_/$id/edit'
import { Route as LocaleSettingsApikeysIdDeleteRouteImport } from './routes/$locale/settings/apikeys_/$id/delete'
import { Route as LocaleActivityAiTasksIdRefreshRouteImport } from './routes/$locale/activity/ai-tasks_/$id/refresh'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings_',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NoPermissionRoute = NoPermissionRouteImport.update({
  id: '/no-permission',
  path: '/no-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImagesRoute = MyImagesRouteImport.update({
  id: '/my-images',
  path: '/my-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs_',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat_',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog_',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMusicGeneratorRoute = AiMusicGeneratorRouteImport.update({
  id: '/ai-music-generator',
  path: '/ai-music-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageGeneratorRoute = AiImageGeneratorRouteImport.update({
  id: '/ai-image-generator',
  path: '/ai-image-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity_',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/settings/apikeys',
  path: '/settings/apikeys',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSplatRoute = ChatSplatRouteImport.update({
  id: '/chat/$',
  path: '/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityFeedbacksRoute = ActivityFeedbacksRouteImport.update({
  id: '/activity/feedbacks',
  path: '/activity/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityChatsRoute = ActivityChatsRouteImport.update({
  id: '/activity/chats',
  path: '/activity/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityAiTasksRoute = ActivityAiTasksRouteImport.update({
  id: '/activity/ai-tasks',
  path: '/activity/ai-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignUpRoute = LocaleSignUpRouteImport.update({
  id: '/$locale/sign-up',
  path: '/$locale/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/$locale/sign-in',
  path: '/$locale/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/$locale/settings_',
  path: '/$locale/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/$locale/reset-password',
  path: '/$locale/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/$locale/pricing',
  path: '/$locale/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleNoPermissionRoute = LocaleNoPermissionRouteImport.update({
  id: '/$locale/no-permission',
  path: '/$locale/no-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMyImagesRoute = LocaleMyImagesRouteImport.update({
  id: '/$locale/my-images',
  path: '/$locale/my-images',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/$locale/forgot-password',
  path: '/$locale/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsRoute = LocaleDocsRouteImport.update({
  id: '/$locale/docs_',
  path: '/$locale/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleChatRoute = LocaleChatRouteImport.update({
  id: '/$locale/chat_',
  path: '/$locale/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/$locale/blog_',
  path: '/$locale/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAiMusicGeneratorRoute = LocaleAiMusicGeneratorRouteImport.update({
  id: '/$locale/ai-music-generator',
  path: '/$locale/ai-music-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAiImageGeneratorRoute = LocaleAiImageGeneratorRouteImport.update({
  id: '/$locale/ai-image-generator',
  path: '/$locale/ai-image-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/$locale/admin_',
  path: '/$locale/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityRoute = LocaleActivityRouteImport.update({
  id: '/$locale/activity_',
  path: '/$locale/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInvoicesRetrieveRoute =
  SettingsInvoicesRetrieveRouteImport.update({
    id: '/settings/invoices/retrieve',
    path: '/settings/invoices/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBillingRetrieveRoute = SettingsBillingRetrieveRouteImport.update({
  id: '/settings/billing_/retrieve',
  path: '/settings/billing/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingCancelRoute = SettingsBillingCancelRouteImport.update({
  id: '/settings/billing_/cancel',
  path: '/settings/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApikeysCreateRoute = SettingsApikeysCreateRouteImport.update({
  id: '/settings/apikeys_/create',
  path: '/settings/apikeys/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSelfDetailsRoute = ApiUserSelfDetailsRouteImport.update({
  id: '/api/user/self-details',
  path: '/api/user/self-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGetUserCreditsRoute = ApiUserGetUserCreditsRouteImport.update({
  id: '/api/user/get-user-credits',
  path: '/api/user/get-user-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsQuotaRoute = ApiTtsQuotaRouteImport.update({
  id: '/api/tts/quota',
  path: '/api/tts/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsHistoryRoute = ApiTtsHistoryRouteImport.update({
  id: '/api/tts/history',
  path: '/api/tts/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsGenerateRoute = ApiTtsGenerateRouteImport.update({
  id: '/api/tts/generate',
  path: '/api/tts/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadImageRoute = ApiStorageUploadImageRouteImport.update({
  id: '/api/storage/upload-image',
  path: '/api/storage/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoverUploadRoute = ApiRemoverUploadRouteImport.update({
  id: '/api/remover/upload',
  path: '/api/remover/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoverJobsRoute = ApiRemoverJobsRouteImport.update({
  id: '/api/remover/jobs',
  path: '/api/remover/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoverCleanupRoute = ApiRemoverCleanupRouteImport.update({
  id: '/api/remover/cleanup',
  path: '/api/remover/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentNotifyRoute = ApiPaymentNotifyRouteImport.update({
  id: '/api/payment/notify',
  path: '/api/payment/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment/callback',
  path: '/api/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailVerifyCodeRoute = ApiEmailVerifyCodeRouteImport.update({
  id: '/api/email/verify-code',
  path: '/api/email/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailTestRoute = ApiEmailTestRouteImport.update({
  id: '/api/email/test',
  path: '/api/email/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendEmailRoute = ApiEmailSendEmailRouteImport.update({
  id: '/api/email/send-email',
  path: '/api/email/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs/search',
  path: '/api/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigGetConfigsRoute = ApiConfigGetConfigsRouteImport.update({
  id: '/api/config/get-configs',
  path: '/api/config/get-configs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatNewRoute = ApiChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatListRoute = ApiChatListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatInfoRoute = ApiChatInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiBackgroundRemoverRemoveRoute =
  ApiBackgroundRemoverRemoveRouteImport.update({
    id: '/api/background-remover/remove',
    path: '/api/background-remover/remove',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBackgroundRemoverCleanupRoute =
  ApiBackgroundRemoverCleanupRouteImport.update({
    id: '/api/background-remover/cleanup',
    path: '/api/background-remover/cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAiQueryRoute = ApiAiQueryRouteImport.update({
  id: '/api/ai/query',
  path: '/api/ai/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCapabilitiesRoute = ApiAiCapabilitiesRouteImport.update({
  id: '/api/ai/capabilities',
  path: '/api/ai/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsSecurityRoute = LocaleSettingsSecurityRouteImport.update({
  id: '/$locale/settings/security',
  path: '/$locale/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsProfileRoute = LocaleSettingsProfileRouteImport.update({
  id: '/$locale/settings/profile',
  path: '/$locale/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsPaymentsRoute = LocaleSettingsPaymentsRouteImport.update({
  id: '/$locale/settings/payments',
  path: '/$locale/settings/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsCreditsRoute = LocaleSettingsCreditsRouteImport.update({
  id: '/$locale/settings/credits',
  path: '/$locale/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsBillingRoute = LocaleSettingsBillingRouteImport.update({
  id: '/$locale/settings/billing',
  path: '/$locale/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsApikeysRoute = LocaleSettingsApikeysRouteImport.update({
  id: '/$locale/settings/apikeys',
  path: '/$locale/settings/apikeys',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsSplatRoute = LocaleDocsSplatRouteImport.update({
  id: '/$locale/docs/$',
  path: '/$locale/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleChatSplatRoute = LocaleChatSplatRouteImport.update({
  id: '/$locale/chat/$',
  path: '/$locale/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAdminSplatRoute = LocaleAdminSplatRouteImport.update({
  id: '/$locale/admin/$',
  path: '/$locale/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityFeedbacksRoute = LocaleActivityFeedbacksRouteImport.update({
  id: '/$locale/activity/feedbacks',
  path: '/$locale/activity/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityChatsRoute = LocaleActivityChatsRouteImport.update({
  id: '/$locale/activity/chats',
  path: '/$locale/activity/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityAiTasksRoute = LocaleActivityAiTasksRouteImport.update({
  id: '/$locale/activity/ai-tasks',
  path: '/$locale/activity/ai-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApikeysIdEditRoute = SettingsApikeysIdEditRouteImport.update({
  id: '/settings/apikeys_/$id/edit',
  path: '/settings/apikeys/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApikeysIdDeleteRoute = SettingsApikeysIdDeleteRouteImport.update({
  id: '/settings/apikeys_/$id/delete',
  path: '/settings/apikeys/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsDownloadIdRoute = ApiTtsDownloadIdRouteImport.update({
  id: '/api/tts/download/$id',
  path: '/api/tts/download/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoverJobsIdRoute = ApiRemoverJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRemoverJobsRoute,
} as any)
const ApiRemoverDownloadLowResRoute =
  ApiRemoverDownloadLowResRouteImport.update({
    id: '/api/remover/download/low-res',
    path: '/api/remover/download/low-res',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRemoverDownloadHighResRoute =
  ApiRemoverDownloadHighResRouteImport.update({
    id: '/api/remover/download/high-res',
    path: '/api/remover/download/high-res',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBackgroundRemoverResultIdRoute =
  ApiBackgroundRemoverResultIdRouteImport.update({
    id: '/api/background-remover/result/$id',
    path: '/api/background-remover/result/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBackgroundRemoverDownloadIdRoute =
  ApiBackgroundRemoverDownloadIdRouteImport.update({
    id: '/api/background-remover/download/$id',
    path: '/api/background-remover/download/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiNotifyProviderRoute = ApiAiNotifyProviderRouteImport.update({
  id: '/api/ai/notify/$provider',
  path: '/api/ai/notify/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityAiTasksIdRefreshRoute =
  ActivityAiTasksIdRefreshRouteImport.update({
    id: '/activity/ai-tasks_/$id/refresh',
    path: '/activity/ai-tasks/$id/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsInvoicesRetrieveRoute =
  LocaleSettingsInvoicesRetrieveRouteImport.update({
    id: '/$locale/settings/invoices/retrieve',
    path: '/$locale/settings/invoices/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsBillingRetrieveRoute =
  LocaleSettingsBillingRetrieveRouteImport.update({
    id: '/$locale/settings/billing_/retrieve',
    path: '/$locale/settings/billing/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsBillingCancelRoute =
  LocaleSettingsBillingCancelRouteImport.update({
    id: '/$locale/settings/billing_/cancel',
    path: '/$locale/settings/billing/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsApikeysCreateRoute =
  LocaleSettingsApikeysCreateRouteImport.update({
    id: '/$locale/settings/apikeys_/create',
    path: '/$locale/settings/apikeys/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleBlogCategorySlugRoute = LocaleBlogCategorySlugRouteImport.update({
  id: '/$locale/blog/category/$slug',
  path: '/$locale/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsApikeysIdEditRoute =
  LocaleSettingsApikeysIdEditRouteImport.update({
    id: '/$locale/settings/apikeys_/$id/edit',
    path: '/$locale/settings/apikeys/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsApikeysIdDeleteRoute =
  LocaleSettingsApikeysIdDeleteRouteImport.update({
    id: '/$locale/settings/apikeys_/$id/delete',
    path: '/$locale/settings/apikeys/$id/delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleActivityAiTasksIdRefreshRoute =
  LocaleActivityAiTasksIdRefreshRouteImport.update({
    id: '/$locale/activity/ai-tasks_/$id/refresh',
    path: '/$locale/activity/ai-tasks/$id/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-music-generator': typeof AiMusicGeneratorRoute
  '/blog': typeof BlogRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-images': typeof MyImagesRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/admin': typeof LocaleAdminRoute
  '/$locale/ai-image-generator': typeof LocaleAiImageGeneratorRoute
  '/$locale/ai-music-generator': typeof LocaleAiMusicGeneratorRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/chat': typeof LocaleChatRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/my-images': typeof LocaleMyImagesRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/activity/ai-tasks': typeof ActivityAiTasksRoute
  '/activity/chats': typeof ActivityChatsRoute
  '/activity/feedbacks': typeof ActivityFeedbacksRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/chat/$': typeof ChatSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/activity/ai-tasks': typeof LocaleActivityAiTasksRoute
  '/$locale/activity/chats': typeof LocaleActivityChatsRoute
  '/$locale/activity/feedbacks': typeof LocaleActivityFeedbacksRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/chat/$': typeof LocaleChatSplatRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/$locale/settings/apikeys': typeof LocaleSettingsApikeysRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/ai/capabilities': typeof ApiAiCapabilitiesRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/query': typeof ApiAiQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/background-remover/cleanup': typeof ApiBackgroundRemoverCleanupRoute
  '/api/background-remover/remove': typeof ApiBackgroundRemoverRemoveRoute
  '/api/chat/info': typeof ApiChatInfoRoute
  '/api/chat/list': typeof ApiChatListRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/config/get-configs': typeof ApiConfigGetConfigsRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/email/send-email': typeof ApiEmailSendEmailRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/remover/cleanup': typeof ApiRemoverCleanupRoute
  '/api/remover/jobs': typeof ApiRemoverJobsRouteWithChildren
  '/api/remover/upload': typeof ApiRemoverUploadRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tts/generate': typeof ApiTtsGenerateRoute
  '/api/tts/history': typeof ApiTtsHistoryRoute
  '/api/tts/quota': typeof ApiTtsQuotaRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/api/user/self-details': typeof ApiUserSelfDetailsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/apikeys/create': typeof SettingsApikeysCreateRoute
  '/settings/billing/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/apikeys/create': typeof LocaleSettingsApikeysCreateRoute
  '/$locale/settings/billing/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
  '/activity/ai-tasks/$id/refresh': typeof ActivityAiTasksIdRefreshRoute
  '/api/ai/notify/$provider': typeof ApiAiNotifyProviderRoute
  '/api/background-remover/download/$id': typeof ApiBackgroundRemoverDownloadIdRoute
  '/api/background-remover/result/$id': typeof ApiBackgroundRemoverResultIdRoute
  '/api/remover/download/high-res': typeof ApiRemoverDownloadHighResRoute
  '/api/remover/download/low-res': typeof ApiRemoverDownloadLowResRoute
  '/api/remover/jobs/$id': typeof ApiRemoverJobsIdRoute
  '/api/tts/download/$id': typeof ApiTtsDownloadIdRoute
  '/settings/apikeys/$id/delete': typeof SettingsApikeysIdDeleteRoute
  '/settings/apikeys/$id/edit': typeof SettingsApikeysIdEditRoute
  '/$locale/activity/ai-tasks/$id/refresh': typeof LocaleActivityAiTasksIdRefreshRoute
  '/$locale/settings/apikeys/$id/delete': typeof LocaleSettingsApikeysIdDeleteRoute
  '/$locale/settings/apikeys/$id/edit': typeof LocaleSettingsApikeysIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-music-generator': typeof AiMusicGeneratorRoute
  '/blog': typeof BlogRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-images': typeof MyImagesRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/admin': typeof LocaleAdminRoute
  '/$locale/ai-image-generator': typeof LocaleAiImageGeneratorRoute
  '/$locale/ai-music-generator': typeof LocaleAiMusicGeneratorRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/chat': typeof LocaleChatRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/my-images': typeof LocaleMyImagesRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/activity/ai-tasks': typeof ActivityAiTasksRoute
  '/activity/chats': typeof ActivityChatsRoute
  '/activity/feedbacks': typeof ActivityFeedbacksRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/chat/$': typeof ChatSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/activity/ai-tasks': typeof LocaleActivityAiTasksRoute
  '/$locale/activity/chats': typeof LocaleActivityChatsRoute
  '/$locale/activity/feedbacks': typeof LocaleActivityFeedbacksRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/chat/$': typeof LocaleChatSplatRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/$locale/settings/apikeys': typeof LocaleSettingsApikeysRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/ai/capabilities': typeof ApiAiCapabilitiesRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/query': typeof ApiAiQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/background-remover/cleanup': typeof ApiBackgroundRemoverCleanupRoute
  '/api/background-remover/remove': typeof ApiBackgroundRemoverRemoveRoute
  '/api/chat/info': typeof ApiChatInfoRoute
  '/api/chat/list': typeof ApiChatListRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/config/get-configs': typeof ApiConfigGetConfigsRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/email/send-email': typeof ApiEmailSendEmailRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/remover/cleanup': typeof ApiRemoverCleanupRoute
  '/api/remover/jobs': typeof ApiRemoverJobsRouteWithChildren
  '/api/remover/upload': typeof ApiRemoverUploadRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tts/generate': typeof ApiTtsGenerateRoute
  '/api/tts/history': typeof ApiTtsHistoryRoute
  '/api/tts/quota': typeof ApiTtsQuotaRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/api/user/self-details': typeof ApiUserSelfDetailsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/apikeys/create': typeof SettingsApikeysCreateRoute
  '/settings/billing/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/apikeys/create': typeof LocaleSettingsApikeysCreateRoute
  '/$locale/settings/billing/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
  '/activity/ai-tasks/$id/refresh': typeof ActivityAiTasksIdRefreshRoute
  '/api/ai/notify/$provider': typeof ApiAiNotifyProviderRoute
  '/api/background-remover/download/$id': typeof ApiBackgroundRemoverDownloadIdRoute
  '/api/background-remover/result/$id': typeof ApiBackgroundRemoverResultIdRoute
  '/api/remover/download/high-res': typeof ApiRemoverDownloadHighResRoute
  '/api/remover/download/low-res': typeof ApiRemoverDownloadLowResRoute
  '/api/remover/jobs/$id': typeof ApiRemoverJobsIdRoute
  '/api/tts/download/$id': typeof ApiTtsDownloadIdRoute
  '/settings/apikeys/$id/delete': typeof SettingsApikeysIdDeleteRoute
  '/settings/apikeys/$id/edit': typeof SettingsApikeysIdEditRoute
  '/$locale/activity/ai-tasks/$id/refresh': typeof LocaleActivityAiTasksIdRefreshRoute
  '/$locale/settings/apikeys/$id/delete': typeof LocaleSettingsApikeysIdDeleteRoute
  '/$locale/settings/apikeys/$id/edit': typeof LocaleSettingsApikeysIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity_': typeof ActivityRoute
  '/admin_': typeof AdminRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/ai-image-generator': typeof AiImageGeneratorRoute
  '/ai-music-generator': typeof AiMusicGeneratorRoute
  '/blog_': typeof BlogRoute
  '/chat_': typeof ChatRoute
  '/docs_': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-images': typeof MyImagesRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings_': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity_': typeof LocaleActivityRoute
  '/$locale/admin_': typeof LocaleAdminRoute
  '/$locale/ai-image-generator': typeof LocaleAiImageGeneratorRoute
  '/$locale/ai-music-generator': typeof LocaleAiMusicGeneratorRoute
  '/$locale/blog_': typeof LocaleBlogRoute
  '/$locale/chat_': typeof LocaleChatRoute
  '/$locale/docs_': typeof LocaleDocsRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/my-images': typeof LocaleMyImagesRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings_': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/activity/ai-tasks': typeof ActivityAiTasksRoute
  '/activity/chats': typeof ActivityChatsRoute
  '/activity/feedbacks': typeof ActivityFeedbacksRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/chat/$': typeof ChatSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/activity/ai-tasks': typeof LocaleActivityAiTasksRoute
  '/$locale/activity/chats': typeof LocaleActivityChatsRoute
  '/$locale/activity/feedbacks': typeof LocaleActivityFeedbacksRoute
  '/$locale/admin/$': typeof LocaleAdminSplatRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/chat/$': typeof LocaleChatSplatRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/$locale/settings/apikeys': typeof LocaleSettingsApikeysRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/ai/capabilities': typeof ApiAiCapabilitiesRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/query': typeof ApiAiQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/background-remover/cleanup': typeof ApiBackgroundRemoverCleanupRoute
  '/api/background-remover/remove': typeof ApiBackgroundRemoverRemoveRoute
  '/api/chat/info': typeof ApiChatInfoRoute
  '/api/chat/list': typeof ApiChatListRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/config/get-configs': typeof ApiConfigGetConfigsRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/email/send-email': typeof ApiEmailSendEmailRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/remover/cleanup': typeof ApiRemoverCleanupRoute
  '/api/remover/jobs': typeof ApiRemoverJobsRouteWithChildren
  '/api/remover/upload': typeof ApiRemoverUploadRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tts/generate': typeof ApiTtsGenerateRoute
  '/api/tts/history': typeof ApiTtsHistoryRoute
  '/api/tts/quota': typeof ApiTtsQuotaRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/api/user/self-details': typeof ApiUserSelfDetailsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/apikeys_/create': typeof SettingsApikeysCreateRoute
  '/settings/billing_/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing_/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/apikeys_/create': typeof LocaleSettingsApikeysCreateRoute
  '/$locale/settings/billing_/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing_/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
  '/activity/ai-tasks_/$id/refresh': typeof ActivityAiTasksIdRefreshRoute
  '/api/ai/notify/$provider': typeof ApiAiNotifyProviderRoute
  '/api/background-remover/download/$id': typeof ApiBackgroundRemoverDownloadIdRoute
  '/api/background-remover/result/$id': typeof ApiBackgroundRemoverResultIdRoute
  '/api/remover/download/high-res': typeof ApiRemoverDownloadHighResRoute
  '/api/remover/download/low-res': typeof ApiRemoverDownloadLowResRoute
  '/api/remover/jobs/$id': typeof ApiRemoverJobsIdRoute
  '/api/tts/download/$id': typeof ApiTtsDownloadIdRoute
  '/settings/apikeys_/$id/delete': typeof SettingsApikeysIdDeleteRoute
  '/settings/apikeys_/$id/edit': typeof SettingsApikeysIdEditRoute
  '/$locale/activity/ai-tasks_/$id/refresh': typeof LocaleActivityAiTasksIdRefreshRoute
  '/$locale/settings/apikeys_/$id/delete': typeof LocaleSettingsApikeysIdDeleteRoute
  '/$locale/settings/apikeys_/$id/edit': typeof LocaleSettingsApikeysIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/activity'
    | '/admin'
    | '/ads.txt'
    | '/ai-image-generator'
    | '/ai-music-generator'
    | '/blog'
    | '/chat'
    | '/docs'
    | '/forgot-password'
    | '/my-images'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale/activity'
    | '/$locale/admin'
    | '/$locale/ai-image-generator'
    | '/$locale/ai-music-generator'
    | '/$locale/blog'
    | '/$locale/chat'
    | '/$locale/docs'
    | '/$locale/forgot-password'
    | '/$locale/my-images'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/activity/ai-tasks'
    | '/activity/chats'
    | '/activity/feedbacks'
    | '/admin/$'
    | '/api/auth'
    | '/api/chat'
    | '/blog/$slug'
    | '/chat/$'
    | '/docs/$'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/activity/ai-tasks'
    | '/$locale/activity/chats'
    | '/$locale/activity/feedbacks'
    | '/$locale/admin/$'
    | '/$locale/blog/$slug'
    | '/$locale/chat/$'
    | '/$locale/docs/$'
    | '/$locale/settings/apikeys'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/ai/capabilities'
    | '/api/ai/generate'
    | '/api/ai/query'
    | '/api/auth/$'
    | '/api/background-remover/cleanup'
    | '/api/background-remover/remove'
    | '/api/chat/info'
    | '/api/chat/list'
    | '/api/chat/messages'
    | '/api/chat/new'
    | '/api/config/get-configs'
    | '/api/docs/search'
    | '/api/email/send-email'
    | '/api/email/test'
    | '/api/email/verify-code'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/remover/cleanup'
    | '/api/remover/jobs'
    | '/api/remover/upload'
    | '/api/storage/upload-image'
    | '/api/tts/generate'
    | '/api/tts/history'
    | '/api/tts/quota'
    | '/api/user/get-user-credits'
    | '/api/user/self-details'
    | '/blog/category/$slug'
    | '/settings/apikeys/create'
    | '/settings/billing/cancel'
    | '/settings/billing/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/apikeys/create'
    | '/$locale/settings/billing/cancel'
    | '/$locale/settings/billing/retrieve'
    | '/$locale/settings/invoices/retrieve'
    | '/activity/ai-tasks/$id/refresh'
    | '/api/ai/notify/$provider'
    | '/api/background-remover/download/$id'
    | '/api/background-remover/result/$id'
    | '/api/remover/download/high-res'
    | '/api/remover/download/low-res'
    | '/api/remover/jobs/$id'
    | '/api/tts/download/$id'
    | '/settings/apikeys/$id/delete'
    | '/settings/apikeys/$id/edit'
    | '/$locale/activity/ai-tasks/$id/refresh'
    | '/$locale/settings/apikeys/$id/delete'
    | '/$locale/settings/apikeys/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/activity'
    | '/admin'
    | '/ads.txt'
    | '/ai-image-generator'
    | '/ai-music-generator'
    | '/blog'
    | '/chat'
    | '/docs'
    | '/forgot-password'
    | '/my-images'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale/activity'
    | '/$locale/admin'
    | '/$locale/ai-image-generator'
    | '/$locale/ai-music-generator'
    | '/$locale/blog'
    | '/$locale/chat'
    | '/$locale/docs'
    | '/$locale/forgot-password'
    | '/$locale/my-images'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/activity/ai-tasks'
    | '/activity/chats'
    | '/activity/feedbacks'
    | '/admin/$'
    | '/api/auth'
    | '/api/chat'
    | '/blog/$slug'
    | '/chat/$'
    | '/docs/$'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/activity/ai-tasks'
    | '/$locale/activity/chats'
    | '/$locale/activity/feedbacks'
    | '/$locale/admin/$'
    | '/$locale/blog/$slug'
    | '/$locale/chat/$'
    | '/$locale/docs/$'
    | '/$locale/settings/apikeys'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/ai/capabilities'
    | '/api/ai/generate'
    | '/api/ai/query'
    | '/api/auth/$'
    | '/api/background-remover/cleanup'
    | '/api/background-remover/remove'
    | '/api/chat/info'
    | '/api/chat/list'
    | '/api/chat/messages'
    | '/api/chat/new'
    | '/api/config/get-configs'
    | '/api/docs/search'
    | '/api/email/send-email'
    | '/api/email/test'
    | '/api/email/verify-code'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/remover/cleanup'
    | '/api/remover/jobs'
    | '/api/remover/upload'
    | '/api/storage/upload-image'
    | '/api/tts/generate'
    | '/api/tts/history'
    | '/api/tts/quota'
    | '/api/user/get-user-credits'
    | '/api/user/self-details'
    | '/blog/category/$slug'
    | '/settings/apikeys/create'
    | '/settings/billing/cancel'
    | '/settings/billing/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/apikeys/create'
    | '/$locale/settings/billing/cancel'
    | '/$locale/settings/billing/retrieve'
    | '/$locale/settings/invoices/retrieve'
    | '/activity/ai-tasks/$id/refresh'
    | '/api/ai/notify/$provider'
    | '/api/background-remover/download/$id'
    | '/api/background-remover/result/$id'
    | '/api/remover/download/high-res'
    | '/api/remover/download/low-res'
    | '/api/remover/jobs/$id'
    | '/api/tts/download/$id'
    | '/settings/apikeys/$id/delete'
    | '/settings/apikeys/$id/edit'
    | '/$locale/activity/ai-tasks/$id/refresh'
    | '/$locale/settings/apikeys/$id/delete'
    | '/$locale/settings/apikeys/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/activity_'
    | '/admin_'
    | '/ads.txt'
    | '/ai-image-generator'
    | '/ai-music-generator'
    | '/blog_'
    | '/chat_'
    | '/docs_'
    | '/forgot-password'
    | '/my-images'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/settings_'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/$locale/activity_'
    | '/$locale/admin_'
    | '/$locale/ai-image-generator'
    | '/$locale/ai-music-generator'
    | '/$locale/blog_'
    | '/$locale/chat_'
    | '/$locale/docs_'
    | '/$locale/forgot-password'
    | '/$locale/my-images'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings_'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/activity/ai-tasks'
    | '/activity/chats'
    | '/activity/feedbacks'
    | '/admin/$'
    | '/api/auth'
    | '/api/chat'
    | '/blog/$slug'
    | '/chat/$'
    | '/docs/$'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/activity/ai-tasks'
    | '/$locale/activity/chats'
    | '/$locale/activity/feedbacks'
    | '/$locale/admin/$'
    | '/$locale/blog/$slug'
    | '/$locale/chat/$'
    | '/$locale/docs/$'
    | '/$locale/settings/apikeys'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/ai/capabilities'
    | '/api/ai/generate'
    | '/api/ai/query'
    | '/api/auth/$'
    | '/api/background-remover/cleanup'
    | '/api/background-remover/remove'
    | '/api/chat/info'
    | '/api/chat/list'
    | '/api/chat/messages'
    | '/api/chat/new'
    | '/api/config/get-configs'
    | '/api/docs/search'
    | '/api/email/send-email'
    | '/api/email/test'
    | '/api/email/verify-code'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/remover/cleanup'
    | '/api/remover/jobs'
    | '/api/remover/upload'
    | '/api/storage/upload-image'
    | '/api/tts/generate'
    | '/api/tts/history'
    | '/api/tts/quota'
    | '/api/user/get-user-credits'
    | '/api/user/self-details'
    | '/blog/category/$slug'
    | '/settings/apikeys_/create'
    | '/settings/billing_/cancel'
    | '/settings/billing_/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/apikeys_/create'
    | '/$locale/settings/billing_/cancel'
    | '/$locale/settings/billing_/retrieve'
    | '/$locale/settings/invoices/retrieve'
    | '/activity/ai-tasks_/$id/refresh'
    | '/api/ai/notify/$provider'
    | '/api/background-remover/download/$id'
    | '/api/background-remover/result/$id'
    | '/api/remover/download/high-res'
    | '/api/remover/download/low-res'
    | '/api/remover/jobs/$id'
    | '/api/tts/download/$id'
    | '/settings/apikeys_/$id/delete'
    | '/settings/apikeys_/$id/edit'
    | '/$locale/activity/ai-tasks_/$id/refresh'
    | '/$locale/settings/apikeys_/$id/delete'
    | '/$locale/settings/apikeys_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  AiImageGeneratorRoute: typeof AiImageGeneratorRoute
  AiMusicGeneratorRoute: typeof AiMusicGeneratorRoute
  BlogRoute: typeof BlogRoute
  ChatRoute: typeof ChatRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MyImagesRoute: typeof MyImagesRoute
  NoPermissionRoute: typeof NoPermissionRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleActivityRoute: typeof LocaleActivityRoute
  LocaleAdminRoute: typeof LocaleAdminRoute
  LocaleAiImageGeneratorRoute: typeof LocaleAiImageGeneratorRoute
  LocaleAiMusicGeneratorRoute: typeof LocaleAiMusicGeneratorRoute
  LocaleBlogRoute: typeof LocaleBlogRoute
  LocaleChatRoute: typeof LocaleChatRoute
  LocaleDocsRoute: typeof LocaleDocsRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleMyImagesRoute: typeof LocaleMyImagesRoute
  LocaleNoPermissionRoute: typeof LocaleNoPermissionRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleSignUpRoute: typeof LocaleSignUpRoute
  ActivityAiTasksRoute: typeof ActivityAiTasksRoute
  ActivityChatsRoute: typeof ActivityChatsRoute
  ActivityFeedbacksRoute: typeof ActivityFeedbacksRoute
  AdminSplatRoute: typeof AdminSplatRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ChatSplatRoute: typeof ChatSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  LocaleActivityAiTasksRoute: typeof LocaleActivityAiTasksRoute
  LocaleActivityChatsRoute: typeof LocaleActivityChatsRoute
  LocaleActivityFeedbacksRoute: typeof LocaleActivityFeedbacksRoute
  LocaleAdminSplatRoute: typeof LocaleAdminSplatRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleChatSplatRoute: typeof LocaleChatSplatRoute
  LocaleDocsSplatRoute: typeof LocaleDocsSplatRoute
  LocaleSettingsApikeysRoute: typeof LocaleSettingsApikeysRoute
  LocaleSettingsBillingRoute: typeof LocaleSettingsBillingRoute
  LocaleSettingsCreditsRoute: typeof LocaleSettingsCreditsRoute
  LocaleSettingsPaymentsRoute: typeof LocaleSettingsPaymentsRoute
  LocaleSettingsProfileRoute: typeof LocaleSettingsProfileRoute
  LocaleSettingsSecurityRoute: typeof LocaleSettingsSecurityRoute
  ApiAiCapabilitiesRoute: typeof ApiAiCapabilitiesRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiAiQueryRoute: typeof ApiAiQueryRoute
  ApiBackgroundRemoverCleanupRoute: typeof ApiBackgroundRemoverCleanupRoute
  ApiBackgroundRemoverRemoveRoute: typeof ApiBackgroundRemoverRemoveRoute
  ApiConfigGetConfigsRoute: typeof ApiConfigGetConfigsRoute
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
  ApiEmailSendEmailRoute: typeof ApiEmailSendEmailRoute
  ApiEmailTestRoute: typeof ApiEmailTestRoute
  ApiEmailVerifyCodeRoute: typeof ApiEmailVerifyCodeRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentNotifyRoute: typeof ApiPaymentNotifyRoute
  ApiRemoverCleanupRoute: typeof ApiRemoverCleanupRoute
  ApiRemoverJobsRoute: typeof ApiRemoverJobsRouteWithChildren
  ApiRemoverUploadRoute: typeof ApiRemoverUploadRoute
  ApiStorageUploadImageRoute: typeof ApiStorageUploadImageRoute
  ApiTtsGenerateRoute: typeof ApiTtsGenerateRoute
  ApiTtsHistoryRoute: typeof ApiTtsHistoryRoute
  ApiTtsQuotaRoute: typeof ApiTtsQuotaRoute
  ApiUserGetUserCreditsRoute: typeof ApiUserGetUserCreditsRoute
  ApiUserSelfDetailsRoute: typeof ApiUserSelfDetailsRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  SettingsApikeysCreateRoute: typeof SettingsApikeysCreateRoute
  SettingsBillingCancelRoute: typeof SettingsBillingCancelRoute
  SettingsBillingRetrieveRoute: typeof SettingsBillingRetrieveRoute
  SettingsInvoicesRetrieveRoute: typeof SettingsInvoicesRetrieveRoute
  LocaleBlogCategorySlugRoute: typeof LocaleBlogCategorySlugRoute
  LocaleSettingsApikeysCreateRoute: typeof LocaleSettingsApikeysCreateRoute
  LocaleSettingsBillingCancelRoute: typeof LocaleSettingsBillingCancelRoute
  LocaleSettingsBillingRetrieveRoute: typeof LocaleSettingsBillingRetrieveRoute
  LocaleSettingsInvoicesRetrieveRoute: typeof LocaleSettingsInvoicesRetrieveRoute
  ActivityAiTasksIdRefreshRoute: typeof ActivityAiTasksIdRefreshRoute
  ApiAiNotifyProviderRoute: typeof ApiAiNotifyProviderRoute
  ApiBackgroundRemoverDownloadIdRoute: typeof ApiBackgroundRemoverDownloadIdRoute
  ApiBackgroundRemoverResultIdRoute: typeof ApiBackgroundRemoverResultIdRoute
  ApiRemoverDownloadHighResRoute: typeof ApiRemoverDownloadHighResRoute
  ApiRemoverDownloadLowResRoute: typeof ApiRemoverDownloadLowResRoute
  ApiTtsDownloadIdRoute: typeof ApiTtsDownloadIdRoute
  SettingsApikeysIdDeleteRoute: typeof SettingsApikeysIdDeleteRoute
  SettingsApikeysIdEditRoute: typeof SettingsApikeysIdEditRoute
  LocaleActivityAiTasksIdRefreshRoute: typeof LocaleActivityAiTasksIdRefreshRoute
  LocaleSettingsApikeysIdDeleteRoute: typeof LocaleSettingsApikeysIdDeleteRoute
  LocaleSettingsApikeysIdEditRoute: typeof LocaleSettingsApikeysIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_': {
      id: '/settings_'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-permission': {
      id: '/no-permission'
      path: '/no-permission'
      fullPath: '/no-permission'
      preLoaderRoute: typeof NoPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-images': {
      id: '/my-images'
      path: '/my-images'
      fullPath: '/my-images'
      preLoaderRoute: typeof MyImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_': {
      id: '/docs_'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat_': {
      id: '/chat_'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_': {
      id: '/blog_'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-music-generator': {
      id: '/ai-music-generator'
      path: '/ai-music-generator'
      fullPath: '/ai-music-generator'
      preLoaderRoute: typeof AiMusicGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-image-generator': {
      id: '/ai-image-generator'
      path: '/ai-image-generator'
      fullPath: '/ai-image-generator'
      preLoaderRoute: typeof AiImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_': {
      id: '/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity_': {
      id: '/activity_'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/settings/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$': {
      id: '/chat/$'
      path: '/chat/$'
      fullPath: '/chat/$'
      preLoaderRoute: typeof ChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/feedbacks': {
      id: '/activity/feedbacks'
      path: '/activity/feedbacks'
      fullPath: '/activity/feedbacks'
      preLoaderRoute: typeof ActivityFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/chats': {
      id: '/activity/chats'
      path: '/activity/chats'
      fullPath: '/activity/chats'
      preLoaderRoute: typeof ActivityChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/ai-tasks': {
      id: '/activity/ai-tasks'
      path: '/activity/ai-tasks'
      fullPath: '/activity/ai-tasks'
      preLoaderRoute: typeof ActivityAiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-up': {
      id: '/$locale/sign-up'
      path: '/$locale/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/$locale/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings_': {
      id: '/$locale/settings_'
      path: '/$locale/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/$locale/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/$locale/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/no-permission': {
      id: '/$locale/no-permission'
      path: '/$locale/no-permission'
      fullPath: '/$locale/no-permission'
      preLoaderRoute: typeof LocaleNoPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/my-images': {
      id: '/$locale/my-images'
      path: '/$locale/my-images'
      fullPath: '/$locale/my-images'
      preLoaderRoute: typeof LocaleMyImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/$locale/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/docs_': {
      id: '/$locale/docs_'
      path: '/$locale/docs'
      fullPath: '/$locale/docs'
      preLoaderRoute: typeof LocaleDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/chat_': {
      id: '/$locale/chat_'
      path: '/$locale/chat'
      fullPath: '/$locale/chat'
      preLoaderRoute: typeof LocaleChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog_': {
      id: '/$locale/blog_'
      path: '/$locale/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ai-music-generator': {
      id: '/$locale/ai-music-generator'
      path: '/$locale/ai-music-generator'
      fullPath: '/$locale/ai-music-generator'
      preLoaderRoute: typeof LocaleAiMusicGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/ai-image-generator': {
      id: '/$locale/ai-image-generator'
      path: '/$locale/ai-image-generator'
      fullPath: '/$locale/ai-image-generator'
      preLoaderRoute: typeof LocaleAiImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/admin_': {
      id: '/$locale/admin_'
      path: '/$locale/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity_': {
      id: '/$locale/activity_'
      path: '/$locale/activity'
      fullPath: '/$locale/activity'
      preLoaderRoute: typeof LocaleActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/invoices/retrieve': {
      id: '/settings/invoices/retrieve'
      path: '/settings/invoices/retrieve'
      fullPath: '/settings/invoices/retrieve'
      preLoaderRoute: typeof SettingsInvoicesRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing_/retrieve': {
      id: '/settings/billing_/retrieve'
      path: '/settings/billing/retrieve'
      fullPath: '/settings/billing/retrieve'
      preLoaderRoute: typeof SettingsBillingRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing_/cancel': {
      id: '/settings/billing_/cancel'
      path: '/settings/billing/cancel'
      fullPath: '/settings/billing/cancel'
      preLoaderRoute: typeof SettingsBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/apikeys_/create': {
      id: '/settings/apikeys_/create'
      path: '/settings/apikeys/create'
      fullPath: '/settings/apikeys/create'
      preLoaderRoute: typeof SettingsApikeysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/self-details': {
      id: '/api/user/self-details'
      path: '/api/user/self-details'
      fullPath: '/api/user/self-details'
      preLoaderRoute: typeof ApiUserSelfDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/get-user-credits': {
      id: '/api/user/get-user-credits'
      path: '/api/user/get-user-credits'
      fullPath: '/api/user/get-user-credits'
      preLoaderRoute: typeof ApiUserGetUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/quota': {
      id: '/api/tts/quota'
      path: '/api/tts/quota'
      fullPath: '/api/tts/quota'
      preLoaderRoute: typeof ApiTtsQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/history': {
      id: '/api/tts/history'
      path: '/api/tts/history'
      fullPath: '/api/tts/history'
      preLoaderRoute: typeof ApiTtsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/generate': {
      id: '/api/tts/generate'
      path: '/api/tts/generate'
      fullPath: '/api/tts/generate'
      preLoaderRoute: typeof ApiTtsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload-image': {
      id: '/api/storage/upload-image'
      path: '/api/storage/upload-image'
      fullPath: '/api/storage/upload-image'
      preLoaderRoute: typeof ApiStorageUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remover/upload': {
      id: '/api/remover/upload'
      path: '/api/remover/upload'
      fullPath: '/api/remover/upload'
      preLoaderRoute: typeof ApiRemoverUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remover/jobs': {
      id: '/api/remover/jobs'
      path: '/api/remover/jobs'
      fullPath: '/api/remover/jobs'
      preLoaderRoute: typeof ApiRemoverJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remover/cleanup': {
      id: '/api/remover/cleanup'
      path: '/api/remover/cleanup'
      fullPath: '/api/remover/cleanup'
      preLoaderRoute: typeof ApiRemoverCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/notify': {
      id: '/api/payment/notify'
      path: '/api/payment/notify'
      fullPath: '/api/payment/notify'
      preLoaderRoute: typeof ApiPaymentNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/callback': {
      id: '/api/payment/callback'
      path: '/api/payment/callback'
      fullPath: '/api/payment/callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/verify-code': {
      id: '/api/email/verify-code'
      path: '/api/email/verify-code'
      fullPath: '/api/email/verify-code'
      preLoaderRoute: typeof ApiEmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/test': {
      id: '/api/email/test'
      path: '/api/email/test'
      fullPath: '/api/email/test'
      preLoaderRoute: typeof ApiEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send-email': {
      id: '/api/email/send-email'
      path: '/api/email/send-email'
      fullPath: '/api/email/send-email'
      preLoaderRoute: typeof ApiEmailSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/search': {
      id: '/api/docs/search'
      path: '/api/docs/search'
      fullPath: '/api/docs/search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/get-configs': {
      id: '/api/config/get-configs'
      path: '/api/config/get-configs'
      fullPath: '/api/config/get-configs'
      preLoaderRoute: typeof ApiConfigGetConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/new': {
      id: '/api/chat/new'
      path: '/new'
      fullPath: '/api/chat/new'
      preLoaderRoute: typeof ApiChatNewRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/messages': {
      id: '/api/chat/messages'
      path: '/messages'
      fullPath: '/api/chat/messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/list': {
      id: '/api/chat/list'
      path: '/list'
      fullPath: '/api/chat/list'
      preLoaderRoute: typeof ApiChatListRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/info': {
      id: '/api/chat/info'
      path: '/info'
      fullPath: '/api/chat/info'
      preLoaderRoute: typeof ApiChatInfoRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/background-remover/remove': {
      id: '/api/background-remover/remove'
      path: '/api/background-remover/remove'
      fullPath: '/api/background-remover/remove'
      preLoaderRoute: typeof ApiBackgroundRemoverRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/background-remover/cleanup': {
      id: '/api/background-remover/cleanup'
      path: '/api/background-remover/cleanup'
      fullPath: '/api/background-remover/cleanup'
      preLoaderRoute: typeof ApiBackgroundRemoverCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/ai/query': {
      id: '/api/ai/query'
      path: '/api/ai/query'
      fullPath: '/api/ai/query'
      preLoaderRoute: typeof ApiAiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/capabilities': {
      id: '/api/ai/capabilities'
      path: '/api/ai/capabilities'
      fullPath: '/api/ai/capabilities'
      preLoaderRoute: typeof ApiAiCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/security': {
      id: '/$locale/settings/security'
      path: '/$locale/settings/security'
      fullPath: '/$locale/settings/security'
      preLoaderRoute: typeof LocaleSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/profile': {
      id: '/$locale/settings/profile'
      path: '/$locale/settings/profile'
      fullPath: '/$locale/settings/profile'
      preLoaderRoute: typeof LocaleSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/payments': {
      id: '/$locale/settings/payments'
      path: '/$locale/settings/payments'
      fullPath: '/$locale/settings/payments'
      preLoaderRoute: typeof LocaleSettingsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/credits': {
      id: '/$locale/settings/credits'
      path: '/$locale/settings/credits'
      fullPath: '/$locale/settings/credits'
      preLoaderRoute: typeof LocaleSettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing': {
      id: '/$locale/settings/billing'
      path: '/$locale/settings/billing'
      fullPath: '/$locale/settings/billing'
      preLoaderRoute: typeof LocaleSettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/apikeys': {
      id: '/$locale/settings/apikeys'
      path: '/$locale/settings/apikeys'
      fullPath: '/$locale/settings/apikeys'
      preLoaderRoute: typeof LocaleSettingsApikeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/docs/$': {
      id: '/$locale/docs/$'
      path: '/$locale/docs/$'
      fullPath: '/$locale/docs/$'
      preLoaderRoute: typeof LocaleDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/chat/$': {
      id: '/$locale/chat/$'
      path: '/$locale/chat/$'
      fullPath: '/$locale/chat/$'
      preLoaderRoute: typeof LocaleChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/admin/$': {
      id: '/$locale/admin/$'
      path: '/$locale/admin/$'
      fullPath: '/$locale/admin/$'
      preLoaderRoute: typeof LocaleAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity/feedbacks': {
      id: '/$locale/activity/feedbacks'
      path: '/$locale/activity/feedbacks'
      fullPath: '/$locale/activity/feedbacks'
      preLoaderRoute: typeof LocaleActivityFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity/chats': {
      id: '/$locale/activity/chats'
      path: '/$locale/activity/chats'
      fullPath: '/$locale/activity/chats'
      preLoaderRoute: typeof LocaleActivityChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity/ai-tasks': {
      id: '/$locale/activity/ai-tasks'
      path: '/$locale/activity/ai-tasks'
      fullPath: '/$locale/activity/ai-tasks'
      preLoaderRoute: typeof LocaleActivityAiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/apikeys_/$id/edit': {
      id: '/settings/apikeys_/$id/edit'
      path: '/settings/apikeys/$id/edit'
      fullPath: '/settings/apikeys/$id/edit'
      preLoaderRoute: typeof SettingsApikeysIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/apikeys_/$id/delete': {
      id: '/settings/apikeys_/$id/delete'
      path: '/settings/apikeys/$id/delete'
      fullPath: '/settings/apikeys/$id/delete'
      preLoaderRoute: typeof SettingsApikeysIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/download/$id': {
      id: '/api/tts/download/$id'
      path: '/api/tts/download/$id'
      fullPath: '/api/tts/download/$id'
      preLoaderRoute: typeof ApiTtsDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remover/jobs/$id': {
      id: '/api/remover/jobs/$id'
      path: '/$id'
      fullPath: '/api/remover/jobs/$id'
      preLoaderRoute: typeof ApiRemoverJobsIdRouteImport
      parentRoute: typeof ApiRemoverJobsRoute
    }
    '/api/remover/download/low-res': {
      id: '/api/remover/download/low-res'
      path: '/api/remover/download/low-res'
      fullPath: '/api/remover/download/low-res'
      preLoaderRoute: typeof ApiRemoverDownloadLowResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remover/download/high-res': {
      id: '/api/remover/download/high-res'
      path: '/api/remover/download/high-res'
      fullPath: '/api/remover/download/high-res'
      preLoaderRoute: typeof ApiRemoverDownloadHighResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/background-remover/result/$id': {
      id: '/api/background-remover/result/$id'
      path: '/api/background-remover/result/$id'
      fullPath: '/api/background-remover/result/$id'
      preLoaderRoute: typeof ApiBackgroundRemoverResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/background-remover/download/$id': {
      id: '/api/background-remover/download/$id'
      path: '/api/background-remover/download/$id'
      fullPath: '/api/background-remover/download/$id'
      preLoaderRoute: typeof ApiBackgroundRemoverDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/notify/$provider': {
      id: '/api/ai/notify/$provider'
      path: '/api/ai/notify/$provider'
      fullPath: '/api/ai/notify/$provider'
      preLoaderRoute: typeof ApiAiNotifyProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/ai-tasks_/$id/refresh': {
      id: '/activity/ai-tasks_/$id/refresh'
      path: '/activity/ai-tasks/$id/refresh'
      fullPath: '/activity/ai-tasks/$id/refresh'
      preLoaderRoute: typeof ActivityAiTasksIdRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/invoices/retrieve': {
      id: '/$locale/settings/invoices/retrieve'
      path: '/$locale/settings/invoices/retrieve'
      fullPath: '/$locale/settings/invoices/retrieve'
      preLoaderRoute: typeof LocaleSettingsInvoicesRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing_/retrieve': {
      id: '/$locale/settings/billing_/retrieve'
      path: '/$locale/settings/billing/retrieve'
      fullPath: '/$locale/settings/billing/retrieve'
      preLoaderRoute: typeof LocaleSettingsBillingRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing_/cancel': {
      id: '/$locale/settings/billing_/cancel'
      path: '/$locale/settings/billing/cancel'
      fullPath: '/$locale/settings/billing/cancel'
      preLoaderRoute: typeof LocaleSettingsBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/apikeys_/create': {
      id: '/$locale/settings/apikeys_/create'
      path: '/$locale/settings/apikeys/create'
      fullPath: '/$locale/settings/apikeys/create'
      preLoaderRoute: typeof LocaleSettingsApikeysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/category/$slug': {
      id: '/$locale/blog/category/$slug'
      path: '/$locale/blog/category/$slug'
      fullPath: '/$locale/blog/category/$slug'
      preLoaderRoute: typeof LocaleBlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/apikeys_/$id/edit': {
      id: '/$locale/settings/apikeys_/$id/edit'
      path: '/$locale/settings/apikeys/$id/edit'
      fullPath: '/$locale/settings/apikeys/$id/edit'
      preLoaderRoute: typeof LocaleSettingsApikeysIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/apikeys_/$id/delete': {
      id: '/$locale/settings/apikeys_/$id/delete'
      path: '/$locale/settings/apikeys/$id/delete'
      fullPath: '/$locale/settings/apikeys/$id/delete'
      preLoaderRoute: typeof LocaleSettingsApikeysIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity/ai-tasks_/$id/refresh': {
      id: '/$locale/activity/ai-tasks_/$id/refresh'
      path: '/$locale/activity/ai-tasks/$id/refresh'
      fullPath: '/$locale/activity/ai-tasks/$id/refresh'
      preLoaderRoute: typeof LocaleActivityAiTasksIdRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

interface ApiChatRouteChildren {
  ApiChatInfoRoute: typeof ApiChatInfoRoute
  ApiChatListRoute: typeof ApiChatListRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatNewRoute: typeof ApiChatNewRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatInfoRoute: ApiChatInfoRoute,
  ApiChatListRoute: ApiChatListRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatNewRoute: ApiChatNewRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiRemoverJobsRouteChildren {
  ApiRemoverJobsIdRoute: typeof ApiRemoverJobsIdRoute
}

const ApiRemoverJobsRouteChildren: ApiRemoverJobsRouteChildren = {
  ApiRemoverJobsIdRoute: ApiRemoverJobsIdRoute,
}

const ApiRemoverJobsRouteWithChildren = ApiRemoverJobsRoute._addFileChildren(
  ApiRemoverJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  AiImageGeneratorRoute: AiImageGeneratorRoute,
  AiMusicGeneratorRoute: AiMusicGeneratorRoute,
  BlogRoute: BlogRoute,
  ChatRoute: ChatRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MyImagesRoute: MyImagesRoute,
  NoPermissionRoute: NoPermissionRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleActivityRoute: LocaleActivityRoute,
  LocaleAdminRoute: LocaleAdminRoute,
  LocaleAiImageGeneratorRoute: LocaleAiImageGeneratorRoute,
  LocaleAiMusicGeneratorRoute: LocaleAiMusicGeneratorRoute,
  LocaleBlogRoute: LocaleBlogRoute,
  LocaleChatRoute: LocaleChatRoute,
  LocaleDocsRoute: LocaleDocsRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleMyImagesRoute: LocaleMyImagesRoute,
  LocaleNoPermissionRoute: LocaleNoPermissionRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleSignUpRoute: LocaleSignUpRoute,
  ActivityAiTasksRoute: ActivityAiTasksRoute,
  ActivityChatsRoute: ActivityChatsRoute,
  ActivityFeedbacksRoute: ActivityFeedbacksRoute,
  AdminSplatRoute: AdminSplatRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiChatRoute: ApiChatRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ChatSplatRoute: ChatSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  LocaleActivityAiTasksRoute: LocaleActivityAiTasksRoute,
  LocaleActivityChatsRoute: LocaleActivityChatsRoute,
  LocaleActivityFeedbacksRoute: LocaleActivityFeedbacksRoute,
  LocaleAdminSplatRoute: LocaleAdminSplatRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleChatSplatRoute: LocaleChatSplatRoute,
  LocaleDocsSplatRoute: LocaleDocsSplatRoute,
  LocaleSettingsApikeysRoute: LocaleSettingsApikeysRoute,
  LocaleSettingsBillingRoute: LocaleSettingsBillingRoute,
  LocaleSettingsCreditsRoute: LocaleSettingsCreditsRoute,
  LocaleSettingsPaymentsRoute: LocaleSettingsPaymentsRoute,
  LocaleSettingsProfileRoute: LocaleSettingsProfileRoute,
  LocaleSettingsSecurityRoute: LocaleSettingsSecurityRoute,
  ApiAiCapabilitiesRoute: ApiAiCapabilitiesRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiAiQueryRoute: ApiAiQueryRoute,
  ApiBackgroundRemoverCleanupRoute: ApiBackgroundRemoverCleanupRoute,
  ApiBackgroundRemoverRemoveRoute: ApiBackgroundRemoverRemoveRoute,
  ApiConfigGetConfigsRoute: ApiConfigGetConfigsRoute,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
  ApiEmailSendEmailRoute: ApiEmailSendEmailRoute,
  ApiEmailTestRoute: ApiEmailTestRoute,
  ApiEmailVerifyCodeRoute: ApiEmailVerifyCodeRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentNotifyRoute: ApiPaymentNotifyRoute,
  ApiRemoverCleanupRoute: ApiRemoverCleanupRoute,
  ApiRemoverJobsRoute: ApiRemoverJobsRouteWithChildren,
  ApiRemoverUploadRoute: ApiRemoverUploadRoute,
  ApiStorageUploadImageRoute: ApiStorageUploadImageRoute,
  ApiTtsGenerateRoute: ApiTtsGenerateRoute,
  ApiTtsHistoryRoute: ApiTtsHistoryRoute,
  ApiTtsQuotaRoute: ApiTtsQuotaRoute,
  ApiUserGetUserCreditsRoute: ApiUserGetUserCreditsRoute,
  ApiUserSelfDetailsRoute: ApiUserSelfDetailsRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  SettingsApikeysCreateRoute: SettingsApikeysCreateRoute,
  SettingsBillingCancelRoute: SettingsBillingCancelRoute,
  SettingsBillingRetrieveRoute: SettingsBillingRetrieveRoute,
  SettingsInvoicesRetrieveRoute: SettingsInvoicesRetrieveRoute,
  LocaleBlogCategorySlugRoute: LocaleBlogCategorySlugRoute,
  LocaleSettingsApikeysCreateRoute: LocaleSettingsApikeysCreateRoute,
  LocaleSettingsBillingCancelRoute: LocaleSettingsBillingCancelRoute,
  LocaleSettingsBillingRetrieveRoute: LocaleSettingsBillingRetrieveRoute,
  LocaleSettingsInvoicesRetrieveRoute: LocaleSettingsInvoicesRetrieveRoute,
  ActivityAiTasksIdRefreshRoute: ActivityAiTasksIdRefreshRoute,
  ApiAiNotifyProviderRoute: ApiAiNotifyProviderRoute,
  ApiBackgroundRemoverDownloadIdRoute: ApiBackgroundRemoverDownloadIdRoute,
  ApiBackgroundRemoverResultIdRoute: ApiBackgroundRemoverResultIdRoute,
  ApiRemoverDownloadHighResRoute: ApiRemoverDownloadHighResRoute,
  ApiRemoverDownloadLowResRoute: ApiRemoverDownloadLowResRoute,
  ApiTtsDownloadIdRoute: ApiTtsDownloadIdRoute,
  SettingsApikeysIdDeleteRoute: SettingsApikeysIdDeleteRoute,
  SettingsApikeysIdEditRoute: SettingsApikeysIdEditRoute,
  LocaleActivityAiTasksIdRefreshRoute: LocaleActivityAiTasksIdRefreshRoute,
  LocaleSettingsApikeysIdDeleteRoute: LocaleSettingsApikeysIdDeleteRoute,
  LocaleSettingsApikeysIdEditRoute: LocaleSettingsApikeysIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
