/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings_'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NoPermissionRouteImport } from './routes/no-permission'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BlogRouteImport } from './routes/blog_'
import { Route as ActivityRouteImport } from './routes/activity_'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentsRouteImport } from './routes/settings/payments'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocaleSignUpRouteImport } from './routes/$locale/sign-up'
import { Route as LocaleSignInRouteImport } from './routes/$locale/sign-in'
import { Route as LocaleSettingsRouteImport } from './routes/$locale/settings_'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale/reset-password'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocaleNoPermissionRouteImport } from './routes/$locale/no-permission'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleBlogRouteImport } from './routes/$locale/blog_'
import { Route as LocaleActivityRouteImport } from './routes/$locale/activity_'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as SettingsInvoicesRetrieveRouteImport } from './routes/settings/invoices/retrieve'
import { Route as SettingsBillingRetrieveRouteImport } from './routes/settings/billing_/retrieve'
import { Route as SettingsBillingCancelRouteImport } from './routes/settings/billing_/cancel'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'
import { Route as ApiUserGetUserCreditsRouteImport } from './routes/api/user/get-user-credits'
import { Route as ApiPaymentNotifyRouteImport } from './routes/api/payment/notify'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as LocaleSettingsSecurityRouteImport } from './routes/$locale/settings/security'
import { Route as LocaleSettingsProfileRouteImport } from './routes/$locale/settings/profile'
import { Route as LocaleSettingsPaymentsRouteImport } from './routes/$locale/settings/payments'
import { Route as LocaleSettingsCreditsRouteImport } from './routes/$locale/settings/credits'
import { Route as LocaleSettingsBillingRouteImport } from './routes/$locale/settings/billing'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as LocaleSettingsInvoicesRetrieveRouteImport } from './routes/$locale/settings/invoices/retrieve'
import { Route as LocaleSettingsBillingRetrieveRouteImport } from './routes/$locale/settings/billing_/retrieve'
import { Route as LocaleSettingsBillingCancelRouteImport } from './routes/$locale/settings/billing_/cancel'
import { Route as LocaleBlogCategorySlugRouteImport } from './routes/$locale/blog/category/$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings_',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NoPermissionRoute = NoPermissionRouteImport.update({
  id: '/no-permission',
  path: '/no-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog_',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity_',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignUpRoute = LocaleSignUpRouteImport.update({
  id: '/$locale/sign-up',
  path: '/$locale/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/$locale/sign-in',
  path: '/$locale/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/$locale/settings_',
  path: '/$locale/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/$locale/reset-password',
  path: '/$locale/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/$locale/pricing',
  path: '/$locale/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleNoPermissionRoute = LocaleNoPermissionRouteImport.update({
  id: '/$locale/no-permission',
  path: '/$locale/no-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/$locale/forgot-password',
  path: '/$locale/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/$locale/blog_',
  path: '/$locale/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityRoute = LocaleActivityRouteImport.update({
  id: '/$locale/activity_',
  path: '/$locale/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInvoicesRetrieveRoute =
  SettingsInvoicesRetrieveRouteImport.update({
    id: '/settings/invoices/retrieve',
    path: '/settings/invoices/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBillingRetrieveRoute = SettingsBillingRetrieveRouteImport.update({
  id: '/settings/billing_/retrieve',
  path: '/settings/billing/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingCancelRoute = SettingsBillingCancelRouteImport.update({
  id: '/settings/billing_/cancel',
  path: '/settings/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGetUserCreditsRoute = ApiUserGetUserCreditsRouteImport.update({
  id: '/api/user/get-user-credits',
  path: '/api/user/get-user-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentNotifyRoute = ApiPaymentNotifyRouteImport.update({
  id: '/api/payment/notify',
  path: '/api/payment/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsSecurityRoute = LocaleSettingsSecurityRouteImport.update({
  id: '/$locale/settings/security',
  path: '/$locale/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsProfileRoute = LocaleSettingsProfileRouteImport.update({
  id: '/$locale/settings/profile',
  path: '/$locale/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsPaymentsRoute = LocaleSettingsPaymentsRouteImport.update({
  id: '/$locale/settings/payments',
  path: '/$locale/settings/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsCreditsRoute = LocaleSettingsCreditsRouteImport.update({
  id: '/$locale/settings/credits',
  path: '/$locale/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsBillingRoute = LocaleSettingsBillingRouteImport.update({
  id: '/$locale/settings/billing',
  path: '/$locale/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsInvoicesRetrieveRoute =
  LocaleSettingsInvoicesRetrieveRouteImport.update({
    id: '/$locale/settings/invoices/retrieve',
    path: '/$locale/settings/invoices/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsBillingRetrieveRoute =
  LocaleSettingsBillingRetrieveRouteImport.update({
    id: '/$locale/settings/billing_/retrieve',
    path: '/$locale/settings/billing/retrieve',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSettingsBillingCancelRoute =
  LocaleSettingsBillingCancelRouteImport.update({
    id: '/$locale/settings/billing_/cancel',
    path: '/$locale/settings/billing/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleBlogCategorySlugRoute = LocaleBlogCategorySlugRouteImport.update({
  id: '/$locale/blog/category/$slug',
  path: '/$locale/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity': typeof ActivityRoute
  '/blog': typeof BlogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/billing/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/billing/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity': typeof ActivityRoute
  '/blog': typeof BlogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/blog': typeof LocaleBlogRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/billing/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/billing/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activity_': typeof ActivityRoute
  '/blog_': typeof BlogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/no-permission': typeof NoPermissionRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings_': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/activity_': typeof LocaleActivityRoute
  '/$locale/blog_': typeof LocaleBlogRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/no-permission': typeof LocaleNoPermissionRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/settings_': typeof LocaleSettingsRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/settings/billing': typeof LocaleSettingsBillingRoute
  '/$locale/settings/credits': typeof LocaleSettingsCreditsRoute
  '/$locale/settings/payments': typeof LocaleSettingsPaymentsRoute
  '/$locale/settings/profile': typeof LocaleSettingsProfileRoute
  '/$locale/settings/security': typeof LocaleSettingsSecurityRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/settings/billing_/cancel': typeof SettingsBillingCancelRoute
  '/settings/billing_/retrieve': typeof SettingsBillingRetrieveRoute
  '/settings/invoices/retrieve': typeof SettingsInvoicesRetrieveRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/settings/billing_/cancel': typeof LocaleSettingsBillingCancelRoute
  '/$locale/settings/billing_/retrieve': typeof LocaleSettingsBillingRetrieveRoute
  '/$locale/settings/invoices/retrieve': typeof LocaleSettingsInvoicesRetrieveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/activity'
    | '/blog'
    | '/forgot-password'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/$locale/$slug'
    | '/$locale/activity'
    | '/$locale/blog'
    | '/$locale/forgot-password'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/blog/$slug'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/blog/$slug'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/settings/billing/cancel'
    | '/settings/billing/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/billing/cancel'
    | '/$locale/settings/billing/retrieve'
    | '/$locale/settings/invoices/retrieve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/activity'
    | '/blog'
    | '/forgot-password'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/$locale/$slug'
    | '/$locale/activity'
    | '/$locale/blog'
    | '/$locale/forgot-password'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/blog/$slug'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/blog/$slug'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/settings/billing/cancel'
    | '/settings/billing/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/billing/cancel'
    | '/$locale/settings/billing/retrieve'
    | '/$locale/settings/invoices/retrieve'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/activity_'
    | '/blog_'
    | '/forgot-password'
    | '/no-permission'
    | '/pricing'
    | '/reset-password'
    | '/settings_'
    | '/sign-in'
    | '/sign-up'
    | '/$locale/$slug'
    | '/$locale/activity_'
    | '/$locale/blog_'
    | '/$locale/forgot-password'
    | '/$locale/no-permission'
    | '/$locale/pricing'
    | '/$locale/reset-password'
    | '/$locale/settings_'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/blog/$slug'
    | '/settings/billing'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/security'
    | '/$locale/blog/$slug'
    | '/$locale/settings/billing'
    | '/$locale/settings/credits'
    | '/$locale/settings/payments'
    | '/$locale/settings/profile'
    | '/$locale/settings/security'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/settings/billing_/cancel'
    | '/settings/billing_/retrieve'
    | '/settings/invoices/retrieve'
    | '/$locale/blog/category/$slug'
    | '/$locale/settings/billing_/cancel'
    | '/$locale/settings/billing_/retrieve'
    | '/$locale/settings/invoices/retrieve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ActivityRoute: typeof ActivityRoute
  BlogRoute: typeof BlogRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NoPermissionRoute: typeof NoPermissionRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleActivityRoute: typeof LocaleActivityRoute
  LocaleBlogRoute: typeof LocaleBlogRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleNoPermissionRoute: typeof LocaleNoPermissionRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleSignUpRoute: typeof LocaleSignUpRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleSettingsBillingRoute: typeof LocaleSettingsBillingRoute
  LocaleSettingsCreditsRoute: typeof LocaleSettingsCreditsRoute
  LocaleSettingsPaymentsRoute: typeof LocaleSettingsPaymentsRoute
  LocaleSettingsProfileRoute: typeof LocaleSettingsProfileRoute
  LocaleSettingsSecurityRoute: typeof LocaleSettingsSecurityRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentNotifyRoute: typeof ApiPaymentNotifyRoute
  ApiUserGetUserCreditsRoute: typeof ApiUserGetUserCreditsRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  SettingsBillingCancelRoute: typeof SettingsBillingCancelRoute
  SettingsBillingRetrieveRoute: typeof SettingsBillingRetrieveRoute
  SettingsInvoicesRetrieveRoute: typeof SettingsInvoicesRetrieveRoute
  LocaleBlogCategorySlugRoute: typeof LocaleBlogCategorySlugRoute
  LocaleSettingsBillingCancelRoute: typeof LocaleSettingsBillingCancelRoute
  LocaleSettingsBillingRetrieveRoute: typeof LocaleSettingsBillingRetrieveRoute
  LocaleSettingsInvoicesRetrieveRoute: typeof LocaleSettingsInvoicesRetrieveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_': {
      id: '/settings_'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-permission': {
      id: '/no-permission'
      path: '/no-permission'
      fullPath: '/no-permission'
      preLoaderRoute: typeof NoPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_': {
      id: '/blog_'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity_': {
      id: '/activity_'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-up': {
      id: '/$locale/sign-up'
      path: '/$locale/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/$locale/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings_': {
      id: '/$locale/settings_'
      path: '/$locale/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/$locale/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/$locale/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/no-permission': {
      id: '/$locale/no-permission'
      path: '/$locale/no-permission'
      fullPath: '/$locale/no-permission'
      preLoaderRoute: typeof LocaleNoPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/$locale/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog_': {
      id: '/$locale/blog_'
      path: '/$locale/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity_': {
      id: '/$locale/activity_'
      path: '/$locale/activity'
      fullPath: '/$locale/activity'
      preLoaderRoute: typeof LocaleActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/invoices/retrieve': {
      id: '/settings/invoices/retrieve'
      path: '/settings/invoices/retrieve'
      fullPath: '/settings/invoices/retrieve'
      preLoaderRoute: typeof SettingsInvoicesRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing_/retrieve': {
      id: '/settings/billing_/retrieve'
      path: '/settings/billing/retrieve'
      fullPath: '/settings/billing/retrieve'
      preLoaderRoute: typeof SettingsBillingRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing_/cancel': {
      id: '/settings/billing_/cancel'
      path: '/settings/billing/cancel'
      fullPath: '/settings/billing/cancel'
      preLoaderRoute: typeof SettingsBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/get-user-credits': {
      id: '/api/user/get-user-credits'
      path: '/api/user/get-user-credits'
      fullPath: '/api/user/get-user-credits'
      preLoaderRoute: typeof ApiUserGetUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/notify': {
      id: '/api/payment/notify'
      path: '/api/payment/notify'
      fullPath: '/api/payment/notify'
      preLoaderRoute: typeof ApiPaymentNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/security': {
      id: '/$locale/settings/security'
      path: '/$locale/settings/security'
      fullPath: '/$locale/settings/security'
      preLoaderRoute: typeof LocaleSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/profile': {
      id: '/$locale/settings/profile'
      path: '/$locale/settings/profile'
      fullPath: '/$locale/settings/profile'
      preLoaderRoute: typeof LocaleSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/payments': {
      id: '/$locale/settings/payments'
      path: '/$locale/settings/payments'
      fullPath: '/$locale/settings/payments'
      preLoaderRoute: typeof LocaleSettingsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/credits': {
      id: '/$locale/settings/credits'
      path: '/$locale/settings/credits'
      fullPath: '/$locale/settings/credits'
      preLoaderRoute: typeof LocaleSettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing': {
      id: '/$locale/settings/billing'
      path: '/$locale/settings/billing'
      fullPath: '/$locale/settings/billing'
      preLoaderRoute: typeof LocaleSettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/invoices/retrieve': {
      id: '/$locale/settings/invoices/retrieve'
      path: '/$locale/settings/invoices/retrieve'
      fullPath: '/$locale/settings/invoices/retrieve'
      preLoaderRoute: typeof LocaleSettingsInvoicesRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing_/retrieve': {
      id: '/$locale/settings/billing_/retrieve'
      path: '/$locale/settings/billing/retrieve'
      fullPath: '/$locale/settings/billing/retrieve'
      preLoaderRoute: typeof LocaleSettingsBillingRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings/billing_/cancel': {
      id: '/$locale/settings/billing_/cancel'
      path: '/$locale/settings/billing/cancel'
      fullPath: '/$locale/settings/billing/cancel'
      preLoaderRoute: typeof LocaleSettingsBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/category/$slug': {
      id: '/$locale/blog/category/$slug'
      path: '/$locale/blog/category/$slug'
      fullPath: '/$locale/blog/category/$slug'
      preLoaderRoute: typeof LocaleBlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ActivityRoute: ActivityRoute,
  BlogRoute: BlogRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NoPermissionRoute: NoPermissionRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleActivityRoute: LocaleActivityRoute,
  LocaleBlogRoute: LocaleBlogRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleNoPermissionRoute: LocaleNoPermissionRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleSignUpRoute: LocaleSignUpRoute,
  BlogSlugRoute: BlogSlugRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleSettingsBillingRoute: LocaleSettingsBillingRoute,
  LocaleSettingsCreditsRoute: LocaleSettingsCreditsRoute,
  LocaleSettingsPaymentsRoute: LocaleSettingsPaymentsRoute,
  LocaleSettingsProfileRoute: LocaleSettingsProfileRoute,
  LocaleSettingsSecurityRoute: LocaleSettingsSecurityRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentNotifyRoute: ApiPaymentNotifyRoute,
  ApiUserGetUserCreditsRoute: ApiUserGetUserCreditsRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  SettingsBillingCancelRoute: SettingsBillingCancelRoute,
  SettingsBillingRetrieveRoute: SettingsBillingRetrieveRoute,
  SettingsInvoicesRetrieveRoute: SettingsInvoicesRetrieveRoute,
  LocaleBlogCategorySlugRoute: LocaleBlogCategorySlugRoute,
  LocaleSettingsBillingCancelRoute: LocaleSettingsBillingCancelRoute,
  LocaleSettingsBillingRetrieveRoute: LocaleSettingsBillingRetrieveRoute,
  LocaleSettingsInvoicesRetrieveRoute: LocaleSettingsInvoicesRetrieveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
