/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocalePricingRouteImport } from './routes/$locale/pricing'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'
import { Route as ApiUserGetUserCreditsRouteImport } from './routes/api/user/get-user-credits'
import { Route as ApiPaymentNotifyRouteImport } from './routes/api/payment/notify'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as LocaleBlogCategorySlugRouteImport } from './routes/$locale/blog/category/$slug'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/$locale/pricing',
  path: '/$locale/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGetUserCreditsRoute = ApiUserGetUserCreditsRouteImport.update({
  id: '/api/user/get-user-credits',
  path: '/api/user/get-user-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentNotifyRoute = ApiPaymentNotifyRouteImport.update({
  id: '/api/payment/notify',
  path: '/api/payment/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$locale/blog/$slug',
  path: '/$locale/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogCategorySlugRoute = LocaleBlogCategorySlugRouteImport.update({
  id: '/$locale/blog/category/$slug',
  path: '/$locale/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/pricing': typeof PricingRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/pricing': typeof PricingRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/pricing': typeof PricingRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/notify': typeof ApiPaymentNotifyRoute
  '/api/user/get-user-credits': typeof ApiUserGetUserCreditsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/pricing'
    | '/$locale/$slug'
    | '/$locale/pricing'
    | '/blog/$slug'
    | '/$locale/blog/$slug'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/$locale/blog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/pricing'
    | '/$locale/$slug'
    | '/$locale/pricing'
    | '/blog/$slug'
    | '/$locale/blog/$slug'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/$locale/blog/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/pricing'
    | '/$locale/$slug'
    | '/$locale/pricing'
    | '/blog/$slug'
    | '/$locale/blog/$slug'
    | '/api/payment/checkout'
    | '/api/payment/notify'
    | '/api/user/get-user-credits'
    | '/blog/category/$slug'
    | '/$locale/blog/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  PricingRoute: typeof PricingRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocalePricingRoute: typeof LocalePricingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentNotifyRoute: typeof ApiPaymentNotifyRoute
  ApiUserGetUserCreditsRoute: typeof ApiUserGetUserCreditsRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  LocaleBlogCategorySlugRoute: typeof LocaleBlogCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/$locale/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/get-user-credits': {
      id: '/api/user/get-user-credits'
      path: '/api/user/get-user-credits'
      fullPath: '/api/user/get-user-credits'
      preLoaderRoute: typeof ApiUserGetUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/notify': {
      id: '/api/payment/notify'
      path: '/api/payment/notify'
      fullPath: '/api/payment/notify'
      preLoaderRoute: typeof ApiPaymentNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$locale/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/category/$slug': {
      id: '/$locale/blog/category/$slug'
      path: '/$locale/blog/category/$slug'
      fullPath: '/$locale/blog/category/$slug'
      preLoaderRoute: typeof LocaleBlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  PricingRoute: PricingRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  LocalePricingRoute: LocalePricingRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentNotifyRoute: ApiPaymentNotifyRoute,
  ApiUserGetUserCreditsRoute: ApiUserGetUserCreditsRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  LocaleBlogCategorySlugRoute: LocaleBlogCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
