import { spawn } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  resolveSiteCloudflareContract,
  type SiteCloudflareContract,
} from './cloudflare/contract';
import {
  assertReleaseEnvironment,
  buildReleaseSteps,
} from './cloudflare/release';
import {
  buildAppWranglerConfig,
  buildStateWranglerConfig,
} from './cloudflare/wrangler';

const rootDir = process.cwd();
const trackedTypesPath = path.resolve(
  rootDir,
  'src/shared/types/cloudflare.d.ts'
);
const stableTypegenHeader =
  '// Generated by Wrangler from the canonical app/state contract.';

type CommandOptions = {
  env?: NodeJS.ProcessEnv;
  capture?: boolean;
};

function run(
  command: string,
  args: string[],
  { env = process.env, capture = false }: CommandOptions = {}
) {
  return new Promise<string>((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: rootDir,
      env,
      stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    });
    let output = '';
    if (capture) {
      child.stdout?.on('data', (chunk) => {
        output += chunk.toString();
      });
      child.stderr?.on('data', (chunk) => {
        output += chunk.toString();
      });
    }
    child.once('error', reject);
    child.once('exit', (code) => {
      if (code !== 0) {
        reject(
          new Error(
            `${command} ${args.join(' ')} exited with code ${code ?? 1}${output ? `\n${output}` : ''}`
          )
        );
        return;
      }
      resolve(output);
    });
  });
}

function parseSiteArg(args: string[]) {
  const value = args
    .find((arg) => arg.startsWith('--site='))
    ?.slice('--site='.length)
    .trim();
  return value || process.env.SITE?.trim();
}

async function writeConfigs(contract: SiteCloudflareContract) {
  const directory = path.resolve(
    rootDir,
    '.generated',
    'cloudflare',
    contract.siteKey
  );
  await mkdir(directory, { recursive: true });
  const appPath = path.join(directory, 'wrangler.app.toml');
  await writeFile(
    appPath,
    buildAppWranglerConfig(contract, {
      rootDir,
      configPath: appPath,
    }),
    'utf8'
  );

  let statePath: string | null = null;
  if (contract.requires.state) {
    statePath = path.join(directory, 'wrangler.state.toml');
    await writeFile(
      statePath,
      buildStateWranglerConfig(contract, {
        rootDir,
        configPath: statePath,
      }),
      'utf8'
    );
  }

  return { appPath, statePath };
}

function assertRequiredRuntimeValues(
  contract: SiteCloudflareContract,
  env: NodeJS.ProcessEnv
) {
  const missing = contract.requiredVars.filter((name) => !env[name]?.trim());
  if (missing.length) {
    throw new Error(
      `SITE=${contract.siteKey} is missing required runtime vars: ${missing.join(', ')}`
    );
  }
}

async function check(contract: SiteCloudflareContract) {
  assertRequiredRuntimeValues(contract, process.env);
  const configs = await writeConfigs(contract);
  console.log(
    `[cf:check] ${contract.siteKey}: app${configs.statePath ? ' + state' : ''}`
  );
}

async function build(contract: SiteCloudflareContract) {
  await check(contract);
  const strict = contract.site.i18n?.strictPublishing === true;
  await run('node', [
    'scripts/check-site-i18n.mjs',
    '--site',
    contract.siteKey,
    ...(strict ? ['--strict'] : []),
  ]);
  await run('pnpm', ['build'], {
    env: { ...process.env, SITE: contract.siteKey },
  });
  const configs = await writeConfigs(contract);
  for (const configPath of [
    ...(configs.statePath ? [configs.statePath] : []),
    configs.appPath,
  ]) {
    await run('pnpm', [
      'exec',
      'wrangler',
      'deploy',
      '--config',
      configPath,
      '--dry-run',
      '--outdir',
      path.resolve(
        rootDir,
        '.generated',
        'cloudflare',
        contract.siteKey,
        'dry-run'
      ),
    ]);
  }
}

async function writeSecretsFile(contract: SiteCloudflareContract) {
  const directory = path.resolve(
    rootDir,
    '.generated',
    'cloudflare',
    contract.siteKey
  );
  await mkdir(directory, { recursive: true });
  const secretsPath = path.join(directory, 'app.secrets.env');
  await writeFile(
    secretsPath,
    contract.requiredSecrets
      .map((name) => `${name}=${process.env[name] ?? ''}`)
      .join('\n') + '\n',
    { encoding: 'utf8', mode: 0o600 }
  );
  return secretsPath;
}

async function deploy(
  contract: SiteCloudflareContract,
  target: 'app' | 'state'
) {
  const configs = await writeConfigs(contract);
  const configPath = target === 'app' ? configs.appPath : configs.statePath;
  if (!configPath) {
    throw new Error(`SITE=${contract.siteKey} has no state worker`);
  }

  const args = [
    'exec',
    'wrangler',
    'deploy',
    '--config',
    configPath,
    '--name',
    contract.workers[target]!,
    '--keep-vars',
  ];
  let secretsPath: string | null = null;
  if (target === 'app') {
    assertReleaseEnvironment(contract, process.env);
    secretsPath = await writeSecretsFile(contract);
    if (contract.requiredSecrets.length) {
      args.push('--secrets-file', secretsPath);
    }
  }

  try {
    await run('pnpm', args);
  } finally {
    if (secretsPath) await rm(secretsPath, { force: true });
  }
}

function normalizeTypes(content: string) {
  return content
    .replace(/^\/\/ Generated by Wrangler by running .*$/m, stableTypegenHeader)
    .replace(/[ \t]+$/gm, '');
}

async function typegen(checkOnly: boolean) {
  const contract = resolveSiteCloudflareContract({
    rootDir,
    siteKey: 'text-to-speech-generator',
  });
  const { appPath } = await writeConfigs(contract);
  const before = await readFile(trackedTypesPath, 'utf8').catch(() => '');
  await run('pnpm', [
    'exec',
    'wrangler',
    'types',
    '--config',
    appPath,
    '--env-interface',
    'CloudflareEnv',
    trackedTypesPath,
  ]);
  const generated = normalizeTypes(await readFile(trackedTypesPath, 'utf8'));

  if (checkOnly) {
    await writeFile(trackedTypesPath, before, 'utf8');
    if (normalizeTypes(before) !== generated) {
      throw new Error(
        'src/shared/types/cloudflare.d.ts is out of date. Run `pnpm cf:typegen`.'
      );
    }
    console.log('[cf:typegen:check] cloudflare.d.ts is current');
    return;
  }
  await writeFile(trackedTypesPath, generated, 'utf8');
}

async function release(contract: SiteCloudflareContract) {
  assertReleaseEnvironment(contract, process.env);
  for (const step of buildReleaseSteps(contract)) {
    await run('pnpm', [step], {
      env: { ...process.env, SITE: contract.siteKey },
    });
  }
}

export async function main(args = process.argv.slice(2)) {
  const command = args[0];
  if (command === 'typegen' || command === 'typegen-check') {
    await typegen(command === 'typegen-check');
    return;
  }

  const siteKey = parseSiteArg(args);
  const contract = resolveSiteCloudflareContract({ rootDir, siteKey });
  switch (command) {
    case 'check':
      await check(contract);
      break;
    case 'build':
      await build(contract);
      break;
    case 'build-no-db':
      await build(contract);
      break;
    case 'deploy-app':
      await deploy(contract, 'app');
      break;
    case 'deploy-state':
      await deploy(contract, 'state');
      break;
    case 'release':
      await release(contract);
      break;
    default:
      throw new Error(`unknown Cloudflare command: ${String(command)}`);
  }
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.stack : String(error));
    process.exit(1);
  });
}
